- .github/workflows/dev_depoly.yml
> application-prod 깃허브 시크릿 추가

- .github/workflows/dev_depoly.yml
> Docker 내부 MYSQL CI환경에 추가

- .github/workflows/dev_depoly.yml
> deploy 쪽 artifact 수정

- .github/workflows/dev_depoly.yml
> 스웨거 배포 환경에 맞게 수정

- .github/workflows/dev_depoly.yml
> 스웨거 배포 환경에 맞게 수정(bootJar)

- .github/workflows/dev_depoly.yml
> 스웨거 배포 환경에 맞게 수정(bootJar) + 이전 캐시 삭제

- src/main/java/com/nexus/seoulmate/member/service/FluentProxyService.java
> #4 
* 언어 별 스크립트 생성해서 포스트 번호 할당
> [MOD/#4] 언어 평가 스크립트 할당

- src/main/java/com/nexus/seoulmate/member/controller/MemberController.java
- src/main/java/com/nexus/seoulmate/member/domain/enums/Countries.java
- src/main/java/com/nexus/seoulmate/member/domain/enums/University.java
- src/main/java/com/nexus/seoulmate/member/dto/signup/ProfileCreateRequest.java
- src/main/java/com/nexus/seoulmate/member/service/MemberService.java
- src/main/java/com/nexus/seoulmate/member/service/TempStorage.java
- src/main/resources/application.yml
> #1 
* @RequestBody, @ReqeustPart 가 Multipart랑 같이 입력받으면 충돌 발생 -> 해결
> [MOD/#1] Request 에러 해결

- src/main/java/com/nexus/seoulmate/friend/converter/FriendConverter.java
> [MERGE] chemistry 관련 코드 삭제

- .github/workflows/dev_depoly.yml
- Dockerfile
- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
> [MERGE] 2025.08.09 자동 배포 안되는 문제 수정

- src/main/java/com/nexus/seoulmate/mock/HobbyDataInitializer.java
> [MERGE] 배포 앱 죽는 에러 해결2

- src/main/java/com/nexus/seoulmate/aws/config/AmazonConfig.java
- src/main/resources/application.yml
> 배포 앱 죽는 에러 해결 - 카멜 케이스로 변경

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
- src/main/java/com/nexus/seoulmate/config/WebConfig.java
> [MERGE] 구글 회원 정보 안불러와짐 해결 1

- build.gradle
- docker-compose.yml
- src/main/java/com/nexus/seoulmate/config/RedisConfig.java
- src/main/resources/application.yml
> [MOD/#46] 도커에서 레디스 사용하도록 설정

- .github/workflows/dev_depoly.yml
> [MERGE] application.yml 수정

- .github/workflows/dev_depoly.yml
- build.gradle
- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
- src/main/java/com/nexus/seoulmate/member/controller/MemberController.java
- src/main/java/com/nexus/seoulmate/member/dto/CustomOAuth2User.java
- src/main/java/com/nexus/seoulmate/member/dto/GoogleResponse.java
- src/main/java/com/nexus/seoulmate/member/service/CustomOAuth2UserService.java
- src/main/resources/application.yml
> #46 
* application 수정
* CustomOAuth2User 생성
* application dev, prod 수정 반영 필요
> [Mod/#46] application 수정, CustomOAuth2User 생성

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
> [MOD/#46] 연동 수정 - AuthenticationSuccessHandler

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
> redirect 대신 forward 사용

- build.gradle
> Revert "spring session redis 의존성 추가"

- src/main/java/com/nexus/seoulmate/common/HealthCheckController.java
- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
> [MERGE] domain 설정

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
- src/main/resources/application.yml
> forward 에서 다시 redirect 사용

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
- src/main/java/com/nexus/seoulmate/exception/status/ErrorStatus.java
- src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
- src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
- src/main/java/com/nexus/seoulmate/meeting/domain/Meeting.java
- src/main/java/com/nexus/seoulmate/notification/api/NotificationController.java
- src/main/java/com/nexus/seoulmate/notification/api/dto/NotificationPushDto.java
- src/main/java/com/nexus/seoulmate/notification/api/dto/response/NotificationReadRes.java
- src/main/java/com/nexus/seoulmate/notification/api/dto/response/NotificationRes.java
- src/main/java/com/nexus/seoulmate/notification/application/NotificationPushService.java
- src/main/java/com/nexus/seoulmate/notification/application/NotificationService.java
- src/main/java/com/nexus/seoulmate/notification/domain/LinkTargetType.java
- src/main/java/com/nexus/seoulmate/notification/domain/Notification.java
- src/main/java/com/nexus/seoulmate/notification/domain/repository/NotificationRepository.java
- src/main/java/com/nexus/seoulmate/notification/event/FriendAcceptedEvent.java
- src/main/java/com/nexus/seoulmate/notification/event/FriendRequestedEvent.java
- src/main/java/com/nexus/seoulmate/notification/event/NotificationEventHandler.java
- src/main/java/com/nexus/seoulmate/notification/event/PaymentCaptureEvent.java
- src/main/java/com/nexus/seoulmate/notification/support/NotificationTemplates.java
- src/main/java/com/nexus/seoulmate/order/domain/Order.java
- src/main/java/com/nexus/seoulmate/order/domain/repository/OrderRepository.java
- src/main/java/com/nexus/seoulmate/payment/application/PaymentService.java
> #56 
* 결제 하면 -> 내 모임에 참여했습니다 (호스트만)
* 친구 신청을 걸면 -> 친구 신청이 왔습니다
* 수락하면 -> 친구 신청을 수락했습니다
> [Feat/#56] 알림 API 구현

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
- src/main/java/com/nexus/seoulmate/config/WebConfig.java
- src/main/java/com/nexus/seoulmate/member/handler/CustomAuthenticationSuccessHandler.java
> #46 
* 레벨테스트 배포 환경에서 cors 오류 발생 -> 해결 시도
* 프론트 리디렉션 배포 url로 수정
> [MOD/#46] 레벨테스트 배포 환경에서 안됨 수정, 프론트 리디렉션 주소 수정

- src/main/java/com/nexus/seoulmate/member/handler/CustomAuthenticationSuccessHandler.java
> [MOD/#46] 프론트 리디렉션 주소 수정

- src/main/java/com/nexus/seoulmate/config/SecurityConfig.java
- src/main/java/com/nexus/seoulmate/config/WebConfig.java
> [MOD/#46] cors 에러 해결

- src/main/java/com/nexus/seoulmate/chat/api/ChatController.java
- src/main/java/com/nexus/seoulmate/chat/application/ChatService.java
- src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
- src/main/java/com/nexus/seoulmate/chat/converter/ChatConverter.java
- src/main/java/com/nexus/seoulmate/chat/domain/entity/ChatRoomMember.java
- src/main/java/com/nexus/seoulmate/chat/domain/repository/ChatRoomMemberRepository.java
- src/main/java/com/nexus/seoulmate/chat/domain/repository/ChatRoomRepository.java
- src/main/java/com/nexus/seoulmate/chat/domain/repository/MessageRepository.java
- src/main/java/com/nexus/seoulmate/chat/dto/ChatRoomDTO.java
- src/main/java/com/nexus/seoulmate/exception/status/SuccessStatus.java
> [Feat/#109] 채팅 안읽은 개수 조회

- src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingCreatePrivateReq.java
- src/main/java/com/nexus/seoulmate/meeting/api/dto/request/privateReq/MeetingUpdatePrivateReq.java
- src/main/java/com/nexus/seoulmate/meeting/application/privateMeeting/PrivateMeetingServiceImpl.java
> [FIX/#99] 사설 모임 string->int 변환 및 검증

- src/main/java/com/nexus/seoulmate/mypage/MyPageController.java
- src/main/java/com/nexus/seoulmate/mypage/MyPageService.java
- src/main/java/com/nexus/seoulmate/mypage/repository/MyMeetingQueryRepository.java
- src/main/java/com/nexus/seoulmate/mypage/repository/MyMeetingQueryRepositoryImpl.java
> [FIX/#108] 주최, 참여 모임 조회 년도, 달 기준으로 수정

- src/main/java/com/nexus/seoulmate/chat/api/ChatWebSocketController.java
> [Mod/#116] websocket으로 실시간성 처리

- src/main/java/com/nexus/seoulmate/chat/api/ChatWebSocketController.java
- src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
- src/main/java/com/nexus/seoulmate/friend/converter/FriendConverter.java
- src/main/java/com/nexus/seoulmate/friend/dto/FriendResponseDTO.java
> [MERGE] 2025.08.21 사용자 상세 조회 반환 값 추가

- src/main/java/com/nexus/seoulmate/chat/api/ChatController.java
- src/main/java/com/nexus/seoulmate/chat/api/ChatWebSocketController.java
- src/main/java/com/nexus/seoulmate/chat/application/ChatService.java
- src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
> [MERGE] 2025.08.22 chat용 getcurrentuser 수정

- src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
> [MERGE] 2025.08.22 수정(getCurrentUser 원상복구)

- src/main/java/com/nexus/seoulmate/mypage/MyPageController.java
> [FIX] import 오류 수정

- Dockerfile
- docker-compose.yml
- src/main/java/com/nexus/seoulmate/chat/application/ChatServiceImpl.java
- src/main/java/com/nexus/seoulmate/chat/converter/ChatConverter.java
- src/main/java/com/nexus/seoulmate/friend/application/FriendServiceImpl.java
- src/main/java/com/nexus/seoulmate/friend/domain/repository/FriendRequestRepository.java
- src/main/java/com/nexus/seoulmate/global/status/ErrorStatus.java
- close #151 
- 친구 삭제 api 로직 수정
- 채팅방 1대1 생성시 title,roomImageUrl 수정
- 서버 타임 UTC->KST로 수정
> [MOD] 친구 삭제 api 수정
